# see https://github.com/haskell-CI/haskell-ci#travisyml-template-for-non-container-based-infrastructure
language: c
os: linux
dist: xenial

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

# env:
#   - GHCVER=7.4.2 CABALVER=1.16
#   - GHCVER=7.6.3 CABALVER=1.16
#   - GHCVER=7.8.4 CABALVER=1.18
#   - GHCVER=7.10.3 CABALVER=1.22
#   - GHCVER=8.0.1 CABALVER=1.24
#   - GHCVER=head CABALVER=1.24

matrix:
  include:
    - env: GHCVER=7.4.2 CABALVER=1.16
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.3 CABALVER=1.16
      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 CABALVER=1.22
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: GHCVER=head CABALVER=1.24
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
   - env: GHCVER=head CABALVER=1.24

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

install:
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests -v2
  - cabal build

  - if [ "$(echo -e "1.20\n$CABALVER" | sort -rV | head -n1)" = "$CABALVER" ]; then
      cabal test --show-details=streaming;
    else
      cabal test --show-details=always;
    fi

