env:
  - GHCVER=7.4.2 CABALVER=1.16
  - GHCVER=7.6.3 CABALVER=1.16
  - GHCVER=7.8.4 CABALVER=1.18
  - GHCVER=7.10.3 CABALVER=1.22
  - GHCVER=head CABALVER=1.22

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=1.22

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version

install:
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests -v2
  - cabal build

  - if [ "$(echo -e "1.20\n$CABALVER" | sort -rV | head -n1)" = "$CABALVER" ]; then
      cabal test --show-details=streaming;
    else
      cabal test --show-details=always;
    fi
