language: haskell

# env:
#   - GHCVER=7.4.2 CABALVER=1.24
#   - GHCVER=7.6.3 CABALVER=1.24
#   - GHCVER=7.8.4 CABALVER=1.24
#   - GHCVER=7.10.3 CABALVER=1.24
#   - GHCVER=8.0.2 CABALVER=1.24
#   - GHCVER=8.2.2 CABALVER=1.24
#   - GHCVER=8.4.4 CABALVER=1.24
#   - GHCVER=8.6.5 CABALVER=1.24
#   - GHCVER=8.8.4 CABALVER=1.24
#   - GHCVER=8.10.2 CABALVER=1.24
#   - GHCVER=head CABALVER=1.24

matrix:
  include:
    - ghc: [7.4.2]
      cabal: "1.24"

  # allow_failures:
  #   - env: GHCVER=head CABALVER=1.24

# cache:
#   directories:
#     - $HOME/.cabal
#     - $HOME/.ghc

# before_install:
#   - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
#   - travis_retry sudo apt-get update
#   - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
#   - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
#   - cabal --version

# install:
#   - travis_retry cabal update
#   - cabal install --only-dependencies --enable-tests

# script:
#   - cabal configure --enable-tests -v2
#   - cabal build
#
#   - if [ "$(echo -e "1.20\n$CABALVER" | sort -rV | head -n1)" = "$CABALVER" ]; then
#       cabal test --show-details=streaming;
#     else
#       cabal test --show-details=always;
#     fi

notifications:
    email: false
