# see https://docs.haskellstack.org/en/stable/travis_ci/

sudo: false
cache:
  directories:
    - $HOME/.stack
    - .stack-work

# env:
#   - GHCVER=7.4.2 CABALVER=1.16
#   - GHCVER=7.6.3 CABALVER=1.16
#   - GHCVER=7.8.4 CABALVER=1.18
#   - GHCVER=7.10.3 CABALVER=1.22
#   - GHCVER=8.0.1 CABALVER=1.24
#   - GHCVER=head CABALVER=1.24

matrix:
  include:
    - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}

  # allow_failures:
  #  - env: GHCVER=head STACK_YAML=stack-nightly.yaml


before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal build
  - stack --no-terminal test
